module.exports = {
  content: [
    "_site/**/*.html", 
    "_site/**/*.js",
    "_site/**/*.liquid",
    "_layouts/**/*.liquid",
    "_includes/**/*.liquid",
    "_posts/**/*.md",
    "_pages/**/*.md"
  ],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: [
    /^navbar-/,
    /^btn-/,
    /^card-/,
    /^modal-/,
    /^fade/,
    /^show/,
    /^active/,
    /^disabled/,
    /^d-/,
    /^text-/,
    /^bg-/,
    /^border-/,
    /^shadow-/,
    /^rounded-/,
    /^position-/,
    /^w-/,
    /^h-/,
    /^m-/,
    /^p-/,
    /^col-/,
    /^row/,
    /^container/,
    /^img-/,
    /^figure/,
    /^table/,
    /^thead/,
    /^tbody/,
    /^tr/,
    /^td/,
    /^th/
  ]
};
